config/routes.rb
Rails.application.routes.draw do
  resources :user_messages

  resources :services

  resources :posts

  resources :reviews

  resources :pages

  root 'application#index'

end

app/models/user_message.rb
class UserMessage < ActiveRecord::Base
end

app/controllers/user_messages_controller.rb
class UserMessagesController < ApplicationController
  before_action :set_user_message, only: [:show, :edit, :update, :destroy]

  # GET /user_messages
  # GET /user_messages.json
  def index
    @user_messages = UserMessage.all
  end

  # GET /user_messages/1
  # GET /user_messages/1.json
  def show
  end

  # GET /user_messages/new
  def new
    @user_message = UserMessage.new
  end

  # GET /user_messages/1/edit
  def edit
  end

  # POST /user_messages
  # POST /user_messages.json
  def create
    @user_message = UserMessage.new(user_message_params)

    respond_to do |format|
      if @user_message.save
        format.html { redirect_to @user_message, notice: 'User message was successfully created.' }
        format.json { render :show, status: :created, location: @user_message }
      else
        format.html { render :new }
        format.json { render json: @user_message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_messages/1
  # PATCH/PUT /user_messages/1.json
  def update
    respond_to do |format|
      if @user_message.update(user_message_params)
        format.html { redirect_to @user_message, notice: 'User message was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_message }
      else
        format.html { render :edit }
        format.json { render json: @user_message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_messages/1
  # DELETE /user_messages/1.json
  def destroy
    @user_message.destroy
    respond_to do |format|
      format.html { redirect_to user_messages_url, notice: 'User message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_message
      @user_message = UserMessage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_message_params
      params.require(:user_message).permit(:name, :email, :message)
    end
end

app/helpers/user_messages_helper.rb
module UserMessagesHelper
end

app/views/user_messages/_form.html.erb
<%= form_for(@user_message) do |f| %>
  <% if @user_message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_message.errors.count, "error") %> prohibited this user_message from being saved:</h2>

      <ul>
      <% @user_message.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :message %><br>
    <%= f.text_area :message %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_messages/edit.html.erb
<h1>Editing user_message</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_message %> |
<%= link_to 'Back', user_messages_path %>

app/views/user_messages/index.html.erb
<h1>Listing user_messages</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Message</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_messages.each do |user_message| %>
      <tr>
        <td><%= user_message.name %></td>
        <td><%= user_message.email %></td>
        <td><%= user_message.message %></td>
        <td><%= link_to 'Show', user_message %></td>
        <td><%= link_to 'Edit', edit_user_message_path(user_message) %></td>
        <td><%= link_to 'Destroy', user_message, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User message', new_user_message_path %>

app/views/user_messages/new.html.erb
<h1>New user_message</h1>

<%= render 'form' %>

<%= link_to 'Back', user_messages_path %>

app/views/user_messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user_message.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user_message.email %>
</p>

<p>
  <strong>Message:</strong>
  <%= @user_message.message %>
</p>

<%= link_to 'Edit', edit_user_message_path(@user_message) %> |
<%= link_to 'Back', user_messages_path %>